### PR TITLE
Fixed ambiguous GPIO numbers in buttons.py example code

### PR DESCRIPTION
**Pull request by ttreker**

### CODE REVIEW

**Comment by ttreker** [comment]
Sorry for 2 commits. Just noticed I should have updated the output text to be accurate.

**Comment by helgibbons** [comment]
This works nicely for me on Pi 5!

**Comment by helgibbons** [comment]
Confirmed working for a customer on a Zero 2 as well. Thanks very much @ttreker (and sorry that it took us so long to merge this!)

**Comment by helgibbons** [comment]
Oops, missed that this wasn't targeting main - I've PRed in your changes on over on #206 . Thanks again for the fix!

**Pull request merged**
