### PR TITLE
Update calendar-phat.py

### PR DESCRIPTION
**Pull request by DanielSSilva**
The commented code was misleading. I think that the set_rotation was from the previous library(?). On this new one, the way that I found to rotate it 180 degrees (use the pi upside down) was through the flips.

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thanks for catching this- I think long-term a `set_rotation` method could be added back into the library. Since the internal `h_flip` and `v_flip` values are used when the buffer is prepared for display, and not to translate draw calls, it should allow dynamic rotation with no problems.

You can also set `h_flip` and `v_flip` in the class constructor:

```python
inky_display = InkyPHAT(colour, h_flip=True, v_flip=True)
```

Which might be a better approach, since if you typo a class property name (unless it's in a `__slots__` based class) it will obligingly set that property without throwing an error, ie the following is also valid but wont actually work:

```python
inky_display.hflip = True
```

Would you like to tweak this to use the class constructor, or shall I do it as part of the merge process?

**Comment by Gadgetoid** [comment]
Actually I'm not so sure about `set_rotate` since the sensible way to do `90` and `270` degree rotations would be to prepare your drawing canvas accordingly and - of course - no permutation of `v_flip` and/or `h_flip` would work for these.

**Comment by DanielSSilva** [comment]
I can make that change into the constructor later today. I'm new to python so I might miss some stuff.
I thought about the possibility to make a function that would simply flip the screen 180 degrees (since I think it makes sense to do this if you use the pi upside down because of the power cable).
It wouldn't be called `rotation` because of the 90 an 270 degrees

**Comment by Gadgetoid** [comment]
Ah if you're new to Python that's all the more reason to give it a go! It sounds like you have some good ideas, and I don't mind providing gentle nudges in the right direction.

**Comment by DanielSSilva** [comment]
I forked the repo and changed the inky.py to add the methods that I mentioned above. What's the correct procedure to test them locally, before creating a PR? How to I explicitly say that I want to use the inky in this repo, instead of the one I've installed through `curl https://get.pimoroni.com/inky | bash`

**Comment by Gadgetoid** [comment]
Going to merge changes so far and dive in to fix the linting errors, since they're useful. Thank you!

**Comment by DanielSSilva** [comment]
hey @Gadgetoid! I'm really sorry for the radio silence. This popped up on my head more than once, but I've been busy with other stuff and didn't really had the time (or motivation to be honest) to grab this back.
But let me know if there's something that I must/can do

**Comment by Gadgetoid** [comment]
No worries at all! Believe me when I say: I know exactly where you're coming from. 😆

Nothing required, I don't think, I'm just cleaning house!

**Pull request merged**
