### PR TITLE
Try #104 again now that tests are fixed - better red colour on older Red HT pHAT

### PR DESCRIPTION
**Pull request by jerbzz**
https://user-images.githubusercontent.com/28573604/113060221-439fa000-91a8-11eb-8a47-83daa4192b7f.jpeg

Makes a big difference!

### CODE REVIEW

**Comment by jerbzz** [comment]
https://github.com/pimoroni/inky/pull/104 is the original

**Comment by Gadgetoid** [comment]
Actually *finding* boards to test this on is going to be a challenge! You might have to bear with me a little.

One concern I have with this change is that the "ink" is very temperature sensitive and thus different LUT values can produce different results for different people- depending on their environment. It's possible this improves things all 'round, but I'll have to try sticking the board in a fridge and on a radiator (don't try this at home, haha) to be sure there aren't any regressions.

**Comment by jerbzz** [comment]
You're welcome - I don't really know what I'm doing but I recognise the importance of "Talk is cheap - show me the code", so any small contributions I can make are hopefully useful. I have no issue with sticking my pHAT in the freezer but less sure about the radiator! Maybe the airing cupboard? 😆

**Comment by donbing** [comment]
I have 2 red inkywhats and one yellow here. if someone can tell me how to perform the required testing, i'd be happy to do so! 

is it just a matter of loading this branch up and displaying an image, putting one in the freezer and one on a radiator, and then checking what colour the things are after 30 mins or so? (i'd upload images obvs)

**Comment by Gadgetoid** [comment]
Just tested the before/after and I don't see quite as drastic a difference. Presumably due to it being really rather hot in here.

Stuck it outside to cool down and still looks fine. I think we can merge this! Thank you for asking though @donbing!

In retrospect a freezer *might* be a little drastic!

**Comment by siddhantvirus** [comment]
Hi !
I just got one of those high-temperature inky phats and it seems like the changes haven't had an effect on the output.
It seems like rolling back version 0.0.4 did fix the problem, as suggested here #66 .
Maybe we could add an if condition where if these particular boards are found [ which is definitely being read from the EEPROM and then labelled as  `Detected Red pHAT (High-Temp) `  in the output ] it makes the approach a little easier for everyone?

**Comment by siddhantvirus** [comment]
@Gadgetoid @jerbzz so I studied the changes between v0.0.4 and v1.1.1 [here](https://github.com/pimoroni/inky/compare/v0.0.4...v1.1.1?diff=split#diff-7c765df312447de522d9c9a74744f63ea06750d3071679603698e90d02ca882c) and seems like we are definitely checking the display type and then assigning the lut type. Also, the luts for red_ht definitely seem to be the same, except that we're using equivalent values in hexadecimal instead of decimal ( I checked all values just to be sure), is there anything else that might be causing the said difference? 
I can upload videos and/ or images showing the stark difference in colours if needed.

**Comment by siddhantvirus** [comment]
Thank You ! 
I'll give it a shot, I did clone the repository separately and try last night , but I'll check again and put an update here

**Pull request merged**
