### PR TITLE
simulation mode wrapper [WIP]

### PR DESCRIPTION
**Pull request by daviehh**
[work-in-progress (WHAT module needs hacky way to flip the buffer, etc...)]

Basically rearraging the codes from https://github.com/pimoroni/inky/pull/14, in order to implement the simulation mode for inky as a wrapper as suggested https://github.com/pimoroni/inky/pull/14#issuecomment-455525380

- added an example(copy from `logo.py`): basically just use ,e.g. 
```python
from inky import InkyMockP as InkyPHAT
```
- changed setup script to install gpio, etc only on pi

Credits:
- code from jedahan in https://github.com/pimoroni/inky/pull/14
- code from the test in this repo (`MockSMBus`, etc)

Todo:
- cleanup

[a bit off-topic but also worth checking out]
https://github.com/microsoft/vscode-remote-release/issues/13

### CODE REVIEW

**Comment by Gadgetoid** [comment]
This is fantastic and works really well, thank you! (actually running it in Linux-on-Windows using Xming)

This was the kick I needed to re-evaluate how Inky works in terms of library dependencies-

I've raised a pull request against your repository with some significant changes to the Inky library itself to better facilitate mocking. I've tidied things up as described here - https://github.com/daviehh/inky/pull/1

I decided to raise as a PR against your code so you can see and comment upon what has changed and possibly make additional changes of your own. Would appreciate your feedback!

**Comment by daviehh** [comment]
tested simulation on mac, and with red inky board on pi 4, works fine so far..

**Comment by Gadgetoid** [comment]
Ahoy! Sorry for the radio silence, I haven't forgotten about this. Will get to final test/merge when time permits.

**Comment by Gadgetoid** [comment]
This works gloriously well even on WSL with XMing. I have a final concern- at least I think it's the last sticking point - in that I'm not entirely sure it's valid to have `install_requires` attempt to check the platform. I think this is parsed when building a package, and thus would generate the wrong rerquirements. Also it would fail on- for example- a Chromebook or other ARM-based, non RPi system.

Since it would be nice to make this library fully device agnostic, it could be worth just removing these dependencies or, possibly, using:

```
    extras_require = {
        'rpi-gpio-output':  ["spidev", "RPi.GPIO", "smbus2"]
    }
```

Also the version should be `0.0.6`.

I'll make these tweaks as part of the rebase & merge.

**Comment by Gadgetoid** [comment]
Okay! Your simulation mode wrapper is in master as of https://github.com/pimoroni/inky/commit/365bdd0d151ed0966768546462751368138e648c

Because I rebased, it's completely broken this PR, but your commits are still in master marked as authored by you and comitted by me. One day I'll fully suss this git mayhem out!

Hopefully some more people will pick up and try this, and we can get it into a release.

**Comment by daviehh** [comment]
thanks a lot!

**Comment by Gadgetoid** [comment]
Have expanded the tests and fixed a few bugs here and there (and generally just taken the opportunity to clean some unrelated things up), will try and test with hardware tomorrow. Thank you!

**Comment by Gadgetoid** [comment]
Found a better solution for handling window/close and avoiding an early exit of the script. See: https://github.com/pimoroni/inky/commit/65f9abb7cb09e2a9d9b31e484a576d230d8c28a1

**Pull request closed without merging**
