### PR TITLE
README: Add SPI CS instructions.

### PR DESCRIPTION
**Pull request by Gadgetoid**
Should help with #202 but is a little lost in the noise here...

### CODE REVIEW

**Comment by crogers3** [comment]
Following-up from my post on #202, when adding this line to /boot/config.txt on a Raspberry Pi Zero W (running Bullseye), I get a new error:

```
SystemExit: Woah there, some pins we need are in use!
  ⚠   Chip Select: (line 8, SPI_CE0_N) currently claimed by spi-bcm2835
```

Are there any additional dtoverlay lines I should try adding?

**Comment by FoxtrotPerry** [comment]
> Following-up from my post on #202, when adding this line to /boot/config.txt on a Raspberry Pi Zero W (running Bullseye), I get a new error:
> 
> ```
> SystemExit: Woah there, some pins we need are in use!
>   ⚠   Chip Select: (line 8, SPI_CE0_N) currently claimed by spi-bcm2835
> ```
> 
> Are there any additional dtoverlay lines I should try adding?

@crogers3 I'd recommend creating a new issue for this since it's not necessarily associated with the fix for the issue I had. It seems like your issue deserves it's own separate triage.

**Comment by crogers3** [comment]
Will do! Will also try running Bookworm to see if it fixes the issue.

**Comment by crogers3** [comment]
Can confirm that after upgrading to Bookworm, the issue resolved once I configured `dtoverlay` per the instructions in this commit.

**Pull request merged**
